[tool.poetry]
package-mode = false
name = "src"
version = "0.1.0"
description = "An online cinema is a digital platform that allows users to select, watch, and purchase access to movies and other video materials via the internet."
authors = []

[tool.poetry.dependencies]
python = "^3.12.3"
fastapi = {extras = ["all"], version = "^0.121.1"}
sqlalchemy = "^2.0.36"
pydantic-settings = "^2.7.0"
tqdm = "^4.67.1"
uvicorn = {extras = ["standard"], version = "^0.38.0"}
psycopg2-binary = "^2.9.10"
alembic = "^1.14.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
email-validator = "^2.2.0"
bcrypt = "4.0.1"
jinja2 = "^3.1.5"
beautifulsoup4 = "^4.12.3"
validators = "^0.34.0"
botocore = "^1.35.99"
pillow = "^11.1.0"
python-multipart = "^0.0.20"
aiosmtplib = "^4.0.0"
asyncpg = "^0.30.0"
aiosqlite = "^0.21.0"
aioboto3 = "^13.4.0"
pandas = "^2.2.3"
aiofiles = "^25.1.0"
fastapi-pagination = "^0.15.5"
slowapi = "^0.1.9"
celery = "^5.6.2"
redis = {extras = ["async"], version = "^7.2.1"}
flower = "^2.0.1"
pytest-postgresql = "^8.0.0"
factory-boy = "^3.3.3"
faker = "^40.5.1"
moto = "^5.1.21"
python-dotenv = "^1.2.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-env = "^1.1.5"
pytest-order = "^1.3.0"
pytest-asyncio = "^0.25.3"
httpx = "^0.28.1"
mypy = "^1.10.0"
ruff = "^0.15.5"
pre-commit = "^4.5.1"
types-aiofiles = "^25.1.0.20251011"
pytest-cov = "^7.0.0"
locust = "^2.43.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
target-version = "py312"
exclude = [
    "alembic",
    "tests",
]
# fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false
skip-magic-trailing-comma = false

[tool.ruff.lint]
extend-select = [
    "F",      # Pyflakes
    "E",      # Pycodestyle errors
    "W",      # Pycodestyle warnings
    "I",      # Import sorting
    "UP",     # Pyupgrade
    "C4",     # Comprehension correctness
    "ISC",    # String concatenation correctness
    "ICN",    # Import conventions
    "RET",    # Return statement rules
    "SIM",    # Simplifications
    "TID",    # Import tidiness
    "PTH",    # pathlib instead of os.path
    "TD",     # TODO comment hygiene
    "B",      # Bugbear
    "D",      # Docstring rules
]

ignore = [
    "D203",  # No blank line before class docstring
    "D213",  # Allow summary line on its own line
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D104",  # Missing docstring in public package
    "D105",  # Missing docstring in magic method
    "D107",  # Missing docstring in __init__
    "D401",  # First line should be in imperative mood
]

# unfixable = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"
