"""check schema after refactor

Revision ID: 53b45f129f7a
Revises: 93ea6a13e939
Create Date: 2026-02-13 11:30:07.829441

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "53b45f129f7a"
down_revision: str | Sequence[str] | None = "93ea6a13e939"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
