"""Add movie_comments table

Revision ID: baebaa901225
Revises: 035edcb5f92b
Create Date: 2026-02-23 16:58:58.909485

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baebaa901225"
down_revision: str | Sequence[str] | None = "035edcb5f92b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"], ["movies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["movie_comments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_movie_comments_movie_id", "movie_comments", ["movie_id"]
    )
    op.create_index(
        "ix_movie_comments_parent_id", "movie_comments", ["parent_id"]
    )
    op.create_index("ix_movie_comments_user_id", "movie_comments", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_movie_comments_user_id", table_name="movie_comments")
    op.drop_index("ix_movie_comments_parent_id", table_name="movie_comments")
    op.drop_index("ix_movie_comments_movie_id", table_name="movie_comments")
    op.drop_table("movie_comments")
    # ### end Alembic commands ###
