FROM nginx:1.27-alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/site.conf /etc/nginx/conf.d/default.conf
COPY nginx/certs /etc/nginx/certs

# Optional: copy static files
# COPY src/static /app/static
