upstream fastapi_backend {
    server web:8000;
    # If scale:
    # server web-2:8000;
    # server web-3:8000;
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name localhost;

    return 301 https://$host:8443$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    # WebSocket support
    location /api/v1/cinema/ws/ {
        proxy_pass http://fastapi_backend;

        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host              $host;
        # FastAPI see the real client IP and protocol
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        proxy_buffering off;  # nginx streams data to the client immediately
    }

    # Static files
    location /static/ {
        alias /app/static/;
        expires 30d;
        access_log off;
    }

    # Regular API traffic
    location / {
        proxy_pass http://fastapi_backend;

        proxy_set_header Host              $host;
        # single originating client IP
        proxy_set_header X-Real-IP         $remote_addr;
        # chain of IPs if there are multiple proxies 
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        # lets FastAPI know the original scheme
        proxy_set_header X-Forwarded-Proto $scheme;

        # Only cache unauthenticated GET responses
        proxy_cache        fastapi_cache;  # cache zone defined in nginx.conf
        proxy_cache_valid  200 10s;  # cache only HTTP 200 responses, for 10 s
        # if request has Authorization header, skip cache & go to backend
        proxy_cache_bypass $http_authorization;
        # if response came from authenticated request, don't store it in cache
        proxy_no_cache     $http_authorization;
    }
}
